# Image Arithmetic and Logical operations in OpenCV

#### 1. Image addition and subtraction

In [2]:
# Necessary imports
import numpy as np
import cv2
import matplotlib.pyplot as plt


In [6]:
#  Creating 8-bit array of one element 200
x = np.uint8([200])
x

array([200], dtype=uint8)

In [7]:
#  Creating 8-bit array of one element 100
y = np.uint8([100])
y

array([100], dtype=uint8)

In [8]:



# Adding our arrays
result = x + y

print("x:'{}' + y:'{}' = '{}'".format(x, y, result))


x:'[200]' + y:'[100]' = '[44]'


In [10]:
#  Creating 8-bit array of one element 200
x = np.uint8([200])
x

array([200], dtype=uint8)

In [11]:
#  Creating 8-bit array of one element 100
y = np.uint8([100])
y

array([100], dtype=uint8)

In [12]:
# Adding our arrays with cv2.add()
result=cv2.add(x,y)
print("x:'{}' + y:'{}' = '{}'".format(x, y, result))

x:'[200]' + y:'[100]' = '[[255]]'


In [14]:
#  Creating 8-bit array of one element 200
x = np.uint8([200])
x

array([200], dtype=uint8)

In [15]:
#  Creating 8-bit array of one element 100
y = np.uint8([100])
y



array([100], dtype=uint8)

In [16]:
# Sbtracting our arrays
result = y - x
print("y:'{}' - x:'{}' = '{}'".format(y, x, result))

y:'[100]' - x:'[200]' = '[156]'


In [17]:
#  Creating 8-bit array of one element 200
x = np.uint8([200])
x

array([200], dtype=uint8)

In [18]:
#  Creating 8-bit array of one element 100
y = np.uint8([100])
y

array([100], dtype=uint8)

In [19]:
# Sbtracting our arrays
result =cv2.subtract(y, x) 
print("y:'{}' - x:'{}' = '{}'".format(y, x, result))

y:'[100]' - x:'[200]' = '[[0]]'


In [20]:
# Creating the first 4 x 4 image with values of 1s
A = np.ones( (4,4), dtype = 'uint8')
A

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

In [21]:
# Changing our values from column 0 to column 2
A[:,0:2] = 128 
print(A)



[[128 128   1   1]
 [128 128   1   1]
 [128 128   1   1]
 [128 128   1   1]]


In [22]:
# The second image of size 4 x 4 is created using randint function
# Creating the second 4 x 4 image with random integer values
B= np.random.randint(0,255,4*4, dtype = 'uint8')
B

array([ 63, 160, 173,  40, 142,  24, 186,  95,  86,  15,  66,  39, 134,
       248, 234,  15], dtype=uint8)

In [23]:
B = B.reshape(  (4,4) )
print(B)

[[ 63 160 173  40]
 [142  24 186  95]
 [ 86  15  66  39]
 [134 248 234  15]]


In [24]:
# Adding two images with cv2.add() function
C_sum_cv2 = cv2.add(A, B)
# Adding two images in Numpy
C_sum  = A + B
print(C_sum_cv2)
print(C_sum)

[[191 255 174  41]
 [255 152 187  96]
 [214 143  67  40]
 [255 255 235  16]]
[[191  32 174  41]
 [ 14 152 187  96]
 [214 143  67  40]
 [  6 120 235  16]]


In [25]:
# Subtracting two images with cv2.subtract() function
C_sub_cv2 = cv2.subtract(B, A)
print(C_sub_cv2)
# Subtracting two images in Numpy
C_sub = B - A
print(C_sub)

[[  0  32 172  39]
 [ 14   0 185  94]
 [  0   0  65  38]
 [  6 120 233  14]]
[[191  32 172  39]
 [ 14 152 185  94]
 [214 143  65  38]
 [  6 120 233  14]]
